# Generated by Django 3.2 on 2024-01-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('تمهيدى', 'تمهيدى (سنة واحدة)'), ('رياض الأطفال', 'رياض الأطفال (KG1)'), ('رياض الأطفال', 'رياض الأطفال (KG2)'), ('الابتدائية', 'الابتدائية (6 سنوات)'), ('الاعدادية', 'الاعدادية (3 سنوات)'), ('الثانوية', 'الثانوية (3 سنوات)')], max_length=20, verbose_name='المرحلة الدراسية')),
                ('class_level', models.CharField(max_length=20, verbose_name='الصف الدراسي')),
                ('section', models.CharField(blank=True, max_length=2, null=True, verbose_name='الفصل الدراسي')),
            ],
            options={
                'verbose_name': 'مادة دراسية',
                'verbose_name_plural': 'مواد دراسية',
            },
        ),
    ]
