# Generated by Django 3.2 on 2024-01-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='class_level',
            field=models.CharField(choices=[], max_length=20, verbose_name='الصف الدراسي'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='section',
            field=models.CharField(blank=True, choices=[], max_length=2, null=True, verbose_name='الفصل الدراسي'),
        ),
    ]
