# Generated by Django 3.2 on 2024-01-24 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'verbose_name': ' المراحل', 'verbose_name_plural': 'المرحلة الدراسية'},
        ),
    ]
