# Generated by Django 3.2 on 2024-01-24 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_stage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'verbose_name': 'المراحل', 'verbose_name_plural': 'المرحلة الدراسية'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': ' الطلاب', 'verbose_name_plural': ' اضافة الطلاب'},
        ),
        migrations.AlterField(
            model_name='student',
            name='national_id',
            field=models.CharField(max_length=14, null=True, validators=[django.core.validators.RegexValidator(code='invalid_national_id', message='يجب أن يحتوي الرقم القومي على 14 رقمًا بدقة.', regex='^\\d{14}$')], verbose_name='الرقم القومي'),
        ),
    ]
