# Generated by Django 3.2 on 2024-01-24 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20240124_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.classlevel', verbose_name='الصف الدراسي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='store.stage', verbose_name='المرحلة الدراسية'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='name',
            field=models.CharField(choices=[('تمهيدى', 'الصف الوحيد'), ('رياض الأطفال', 'KG1'), ('رياض الأطفال', 'KG2'), ('الابتدائية', 'الصف الأول'), ('الابتدائية', 'الصف الثاني'), ('الابتدائية', 'الصف الثالث'), ('الابتدائية', 'الصف الرابع'), ('الابتدائية', 'الصف الخامس'), ('الابتدائية', 'الصف السادس'), ('الاعدادية', 'الصف الأول'), ('الاعدادية', 'الصف الثاني'), ('الاعدادية', 'الصف الثالث'), ('الثانوية', 'الصف الأول'), ('الثانوية', 'الصف الثاني'), ('الثانوية', 'الصف الثالث')], max_length=20, verbose_name='الصف الدراسي'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(choices=[], max_length=2, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='store.classroom', verbose_name='الفصل الدراسي'),
        ),
    ]
