# Generated by Django 3.2 on 2024-01-24 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20240124_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='stage',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=2, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.classroom', verbose_name='الفصل الدراسي'),
        ),
    ]
