# Generated by Django 3.2 on 2024-01-31 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20240124_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المورد')),
                ('phone', models.CharField(max_length=15, verbose_name='رقم تليفون المورد')),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردين',
            },
        ),
        migrations.AlterModelOptions(
            name='classlevel',
            options={'verbose_name': 'الصف', 'verbose_name_plural': ' الصف الدراسى'},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'ترقيم الفصول', 'verbose_name_plural': ' الفصل الدراسى'},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'verbose_name': 'المرحلة', 'verbose_name_plural': 'المراحل الدراسية'},
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('عربي', 'عربي'), ('رياضيات', 'رياضيات'), ('علوم', 'علوم')], max_length=50, verbose_name='المادة الدراسية')),
                ('source', models.CharField(choices=[('وزارة التربية والتعليم', 'وزارة التربية والتعليم'), ('مورد خارجي', 'مورد خارجي')], max_length=50, verbose_name='مصدر التوريد')),
                ('initial_quantity', models.IntegerField(default=0, verbose_name='الكمية الأولية')),
                ('received_quantity', models.IntegerField(default=0, verbose_name='الكمية الواردة')),
                ('available_quantity', models.IntegerField(default=0, verbose_name='الكمية المتاحة')),
                ('term', models.CharField(choices=[('الترم الأول', 'الترم الأول'), ('الترم الثاني', 'الترم الثاني')], max_length=20, verbose_name='الترم الدراسي')),
                ('received_date', models.DateField(verbose_name='تاريخ الاستلام')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.classlevel', verbose_name='الصف الدراسي')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.classroom', verbose_name='الفصل الدراسي')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.stage', verbose_name='المرحلة الدراسية')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'كتاب دراسي',
                'verbose_name_plural': 'كتب دراسية',
            },
        ),
        migrations.CreateModel(
            name='BookDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=20, verbose_name='رقم الإيصال')),
                ('delivery_date', models.DateField(verbose_name='تاريخ التوزيع')),
                ('is_delivered_completely', models.BooleanField(default=False, verbose_name='تم تسليم جميع الكتب')),
                ('books', models.ManyToManyField(to='store.Book', verbose_name='الكتب المسلمة')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.classlevel', verbose_name='الصف الدراسي')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.classroom', verbose_name='الفصل الدراسي')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.stage', verbose_name='المرحلة الدراسية')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'توزيع الكتب',
                'verbose_name_plural': 'توزيع الكتب',
                'unique_together': {('student', 'delivery_date')},
            },
        ),
    ]
