# Generated by Django 3.2 on 2024-01-31 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20240131_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'ترقيم الفصول', 'verbose_name_plural': 'الفصل الدراسى'},
        ),
    ]
