# Generated by Django 3.2 on 2024-01-31 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_classroom_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={},
        ),
    ]
