# Generated by Django 3.2 on 2024-01-31 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20240131_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'ترقيم الفصول', 'verbose_name_plural': 'الفصل الدراسى'},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'verbose_name': 'المرحلة', 'verbose_name_plural': 'المراحل الدراسية'},
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='class_levels',
        ),
        migrations.AddField(
            model_name='classroom',
            name='class_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.classlevel', verbose_name='الصف الدراسي'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='stage',
            name='class_levels',
        ),
        migrations.AddField(
            model_name='stage',
            name='class_levels',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.classlevel', verbose_name='الصف الدراسي'),
            preserve_default=False,
        ),
    ]
