# Generated by Django 3.2 on 2024-01-31 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20240131_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='class_level',
        ),
    ]
