# Generated by Django 3.2 on 2024-01-31 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_stage_class_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='class_levels',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.classlevel', verbose_name='الصف الدراسي'),
            preserve_default=False,
        ),
    ]
