# Generated by Django 3.2 on 2024-02-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_stage_class_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='class_levels',
        ),
        migrations.AddField(
            model_name='stage',
            name='class_levels',
            field=models.ManyToManyField(to='store.ClassLevel', verbose_name='الصف الدراسي'),
        ),
    ]
