# Generated by Django 3.2 on 2024-02-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_remove_book_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='stage',
            field=models.CharField(choices=[('تمهيدى', 'تمهيدى (سنة واحدة)'), ('رياض الأطفال ', 'رياض الأطفال '), ('الابتدائية الصف الأول', 'الابتدائية (6 سنوات)'), ('الاعدادية الصف الأول', 'الاعدادية (3 سنوات)'), ('الثانوية الصف الأول', 'الثانوية (3 سنوات)')], max_length=50, verbose_name='المرحلة الدراسية'),
        ),
    ]
