# Generated by Django 3.2 on 2024-02-02 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_stage_stage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'كتاب دراسي', 'verbose_name_plural': 'المواد الدراسية'},
        ),
    ]
