# Generated by Django 3.2 on 2024-02-02 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20240202_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookdistribution',
            options={'verbose_name': 'توزيع الكتب', 'verbose_name_plural': 'توزيع الكتب'},
        ),
        migrations.AlterUniqueTogether(
            name='bookdistribution',
            unique_together={('student', 'delivery_date')},
        ),
    ]
