# Generated by Django 3.2 on 2024-02-06 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_bookdistribution_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='initial_quantity',
        ),
    ]
