# Generated by Django 3.2 on 2024-02-12 10:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_remove_book_initial_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='السنة الدراسية')),
            ],
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='name',
            field=models.CharField(choices=[('تمهيدى', 'تمهيدى'), ('  KG1', 'KG1'), ('  KG2', '  KG2'), ('الابتدائية الصف الأول', 'الابتدائية الصف الأول'), ('الابتدائية الصف الثاني', 'الابتدائية الصف الثاني'), ('الابتدائية الصف الثالث', 'الابتدائية الصف الثالث'), ('الابتدائية الصف الرابع', 'الابتدائية الصف الرابع'), ('الابتدائية الصف الخامس', 'الابتدائية الصف الخامس'), ('الابتدائية الصف السادس', 'الابتدائية الصف السادس'), ('الاعدادية الصف الأول', 'الاعدادية الصف الأول'), ('الاعدادية الصف الثاني', 'الاعدادية الصف الثاني'), ('الاعدادية الصف الثالث', 'الاعدادية الصف الثالث'), ('الثانوية الصف الأول', 'الثانوية الصف الأول'), ('الثانوية الصف الثاني', 'الثانوية الصف الثاني'), ('الثانوية الصف الثالث', 'الثانوية الصف الثالث')], max_length=50, verbose_name='الصف الدراسي'),
        ),
        migrations.AlterField(
            model_name='student',
            name='national_id',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_national_id', message='يجب أن يحتوي الرقم القومي على 14 رقمًا بدقة.', regex='^\\d{14}$')], verbose_name='الرقم القومي'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.academicyear', verbose_name='السنة الدراسية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stage',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.academicyear', verbose_name='السنة الدراسية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='store.academicyear', verbose_name='السنة الدراسية'),
            preserve_default=False,
        ),
    ]
