# Generated by Django 3.2 on 2024-02-13 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_auto_20240212_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'verbose_name': 'السنة', 'verbose_name_plural': '  السنة الدراسية'},
        ),
    ]
