# Generated by Django 3.2 on 2024-02-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_alter_academicyear_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='stage',
            field=models.CharField(choices=[('تمهيدى', 'تمهيدى )'), ('رياض الأطفال ', 'رياض الأطفال '), ('الابتدائية  ', 'الابتدائية '), ('الاعدادية  ', 'الاعدادية '), ('الثانوية  ', 'الثانوية')], max_length=50, verbose_name='المرحلة الدراسية'),
        ),
    ]
