# Generated by Django 3.2 on 2024-02-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_alter_stage_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlevel',
            name='name',
            field=models.CharField(choices=[('تمهيدى', 'تمهيدى'), ('  KG1', 'KG1'), ('  KG2', '  KG2'), ('  PRIM 1', '  PRIM 1'), ('PRIM 2', '  PRIM 2'), ('  PRIM 3', '  PRIM 3'), ('  PRIM 4', '  PRIM 4'), ('  PRIM 5', '  PRIM 5'), ('  PRIM 6', ' PRIM 6 '), ('  PREP 1', '  PREP 1'), ('  PREP 2', ' PREP 2 '), ('  PREP 3', '  PREP 3'), ('  SEC 1', '  SEC 1'), ('  SEC 2', ' SEC 2 '), ('  SEC 3', '  SEC 3')], max_length=50, verbose_name='الصف الدراسي'),
        ),
    ]
