# Generated by Django 3.2 on 2024-02-13 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_auto_20240213_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'كتاب دراسي', 'verbose_name_plural': 'المواد الدراسية'},
        ),
    ]
