# Generated by Django 3.2 on 2024-02-15 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_alter_book_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookdistribution',
            unique_together=set(),
        ),
    ]
