# Generated by Django 3.2 on 2024-02-15 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_alter_bookdistribution_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdistribution',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.classroom', verbose_name='الفصل '),
        ),
        migrations.AlterUniqueTogether(
            name='bookdistribution',
            unique_together={('student', 'delivery_date', 'receipt_number')},
        ),
    ]
