# Generated by Django 3.2 on 2024-02-15 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_auto_20240215_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdistribution',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.classroom', verbose_name='الفصل '),
        ),
    ]
