# Generated by Django 3.2 on 2024-02-19 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_alter_bookdistribution_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdistribution',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.classroom', verbose_name='الفصل الدراسي'),
            preserve_default=False,
        ),
    ]
