# Generated by Django 3.2 on 2024-02-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_alter_bookdistribution_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdistribution',
            name='receipt_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='رقم الإيصال'),
        ),
    ]
