# Generated by Django 3.2 on 2024-02-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_auto_20240219_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stageon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=50, verbose_name='المرحلة ')),
                ('grade', models.CharField(max_length=50, verbose_name='الصف ')),
                ('Classroom', models.CharField(max_length=50, verbose_name='اسم الفصل  ')),
            ],
            options={
                'verbose_name': 'المرحلة',
                'verbose_name_plural': 'المراحل ',
            },
        ),
    ]
