# Generated by Django 3.2 on 2024-02-20 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_stageon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stageon',
        ),
    ]
