# Generated by Django 3.2 on 2024-02-20 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_delete_stageon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSupplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الكراسة أو الأداة المدرسية')),
                ('description', models.TextField(verbose_name='وصف الكراسة أو الأداة المدرسية')),
                ('in_quantity', models.IntegerField(default=0, verbose_name='الكمية الواردة')),
                ('live_quantity', models.IntegerField(default=0, verbose_name='الكمية الحالية')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.classlevel', verbose_name='الصف الدراسي')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.stage', verbose_name='المرحلة الدراسية')),
            ],
            options={
                'verbose_name': 'كراسة أو أداة مدرسية',
                'verbose_name_plural': 'الكراسات والأدوات المدرسية',
            },
        ),
        migrations.CreateModel(
            name='SchoolBooklet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان البوكليت')),
                ('description', models.TextField(verbose_name='وصف البوكليت')),
                ('quantity', models.IntegerField(default=0, verbose_name='الكمية الواردة')),
                ('live_quantity', models.IntegerField(default=0, verbose_name='الكمية الحالية')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.classlevel', verbose_name='الصف الدراسي')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.stage', verbose_name='المرحلة الدراسية')),
            ],
            options={
                'verbose_name': 'بوكليت مدرسي',
                'verbose_name_plural': 'البوكليتات المدرسية',
            },
        ),
    ]
