# Generated by Django 3.2 on 2024-02-21 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_schoolbooklet_schoolsupplies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='class_levels',
        ),
        migrations.AddField(
            model_name='stage',
            name='class_levels',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.classlevel', verbose_name='الصف الدراسي'),
            preserve_default=False,
        ),
    ]
