# Generated by Django 3.2 on 2024-02-21 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_auto_20240221_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stagee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='المرحلة الدراسية')),
            ],
            options={
                'verbose_name': 'المرحلة ',
                'verbose_name_plural': 'المراحل ',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الصف الدراسي')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='store.academicyear', verbose_name='السنة الدراسية')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='store.stagee')),
            ],
            options={
                'verbose_name': 'الصف الدراسي',
                'verbose_name_plural': 'الصفوف الدراسية',
                'unique_together': {('stage', 'name', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='القسم')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='store.grade')),
            ],
            options={
                'verbose_name': 'القسم',
                'verbose_name_plural': 'الأقسام',
                'unique_together': {('grade', 'name')},
            },
        ),
    ]
