# Generated by Django 3.2 on 2024-02-21 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_grade_section_stagee'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlevel',
            name='stage_specific_classrooms',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='name',
            field=models.CharField(choices=[('تمهيدى', 'تمهيدى'), (' KG1', 'KG1'), (' KG2', ' KG2'), (' PRIM 1', ' PRIM 1'), ('PRIM 2', ' PRIM 2'), (' PRIM 3', ' PRIM 3'), (' PRIM 4', ' PRIM 4'), (' PRIM 5', ' PRIM 5'), (' PRIM 6', ' PRIM 6 '), (' PREP 1', ' PREP 1'), (' PREP 2', ' PREP 2 '), (' PREP 3', ' PREP 3'), (' SEC 1', ' SEC 1'), (' SEC 2', ' SEC 2 '), (' SEC 3', ' SEC 3')], max_length=50, verbose_name='الصف الدراسي'),
        ),
        migrations.CreateModel(
            name='StageClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.classlevel')),
                ('classrooms', models.ManyToManyField(to='store.Classroom')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.stage')),
            ],
            options={
                'verbose_name': 'صفوف كل مرحلة',
                'verbose_name_plural': 'صفوف كل مرحلة',
            },
        ),
    ]
