# Generated by Django 3.2 on 2024-02-21 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_auto_20240221_0913'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='section',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='stageclasslevel',
            name='class_level',
        ),
        migrations.RemoveField(
            model_name='stageclasslevel',
            name='classrooms',
        ),
        migrations.RemoveField(
            model_name='stageclasslevel',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='class_levels',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='classrooms',
        ),
        migrations.AddField(
            model_name='classlevel',
            name='stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.stage', verbose_name='المرحلة '),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='classlevel',
            unique_together={('stage', 'name', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('class_levels', 'name')},
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='StageClassLevel',
        ),
        migrations.DeleteModel(
            name='Stagee',
        ),
        migrations.RemoveField(
            model_name='classlevel',
            name='stage_specific_classrooms',
        ),
    ]
