# Generated by Django 3.2 on 2024-02-21 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_auto_20240221_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classlevel',
            options={'verbose_name': 'الصف', 'verbose_name_plural': 'الصف الدراسي'},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'ترقيم الفصول', 'verbose_name_plural': 'الفصل الدراسي'},
        ),
        migrations.AddField(
            model_name='classlevel',
            name='class_name',
            field=models.CharField(choices=[('تمهيدى', 'تمهيدى'), ('KG1', 'KG1'), ('KG2', 'KG2'), ('PRIM 1', 'الصف الابتدائي الأول'), ('PRIM 2', 'الصف الابتدائي الثاني'), ('PRIM 3', 'الصف الابتدائي الثالث'), ('PRIM 4', 'الصف الابتدائي الرابع'), ('PRIM 5', 'الصف الابتدائي الخامس'), ('PRIM 6', 'الصف الابتدائي السادس'), ('PREP 1', 'الصف التحضيري الأول'), ('PREP 2', 'الصف التحضيري الثاني'), ('PREP 3', 'الصف التحضيري الثالث'), ('SEC 1', 'الصف الثانوي الأول'), ('SEC 2', 'الصف الثانوي الثاني'), ('SEC 3', 'الصف الثانوي الثالث')], default=1, max_length=50, verbose_name='اسم الصف الدراسي'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.stage', verbose_name='المرحلة'),
        ),
        migrations.AlterUniqueTogether(
            name='classlevel',
            unique_together={('stage', 'class_name', 'academic_year')},
        ),
        migrations.RemoveField(
            model_name='classlevel',
            name='name',
        ),
    ]
