# Generated by Django 3.2 on 2024-02-21 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_auto_20240221_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classlevel',
            old_name='class_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='classlevel',
            unique_together={('stage', 'name', 'academic_year')},
        ),
    ]
