# Generated by Django 3.2 on 2024-02-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_auto_20240221_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlevel',
            name='name',
            field=models.CharField(choices=[('تمهيدى', 'تمهيدى'), ('KG1', 'KG1'), ('KG2', 'KG2'), ('PRIM 1', 'الصف الابتدائي الأول'), ('PRIM 2', 'الصف الابتدائي الثاني'), ('PRIM 3', 'الصف الابتدائي الثالث'), ('PRIM 4', 'الصف الابتدائي الرابع'), ('PRIM 5', 'الصف الابتدائي الخامس'), ('PRIM 6', 'الصف الابتدائي السادس'), ('PREP 1', 'الصف الاعدادى الأول'), ('PREP 2', 'الصف الاعدادى الثاني'), ('PREP 3', 'الصف الاعدادى الثالث'), ('SEC 1', 'الصف الثانوي الأول'), ('SEC 2', 'الصف الثانوي الثاني'), ('SEC 3', 'الصف الثانوي الثالث')], max_length=50, verbose_name='اسم الصف الدراسي'),
        ),
    ]
