# Generated by Django 3.2 on 2024-02-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_alter_classlevel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default=1, max_length=15, verbose_name='رقم الهاتف'),
            preserve_default=False,
        ),
    ]
