# Generated by Django 3.2 on 2024-02-21 09:30

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_student_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_level',
            field=models.ForeignKey(limit_choices_to={'stage': django.db.models.expressions.F('stage')}, on_delete=django.db.models.deletion.CASCADE, to='store.classlevel', verbose_name='الصف الدراسي'),
        ),
    ]
