# Generated by Django 3.2 on 2024-02-22 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_auto_20240222_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotebookType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نوع الكراسة')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='وصف الكراسة')),
                ('source', models.CharField(choices=[('وزارة التربية والتعليم', 'وزارة التربية والتعليم'), ('مورد خارجي', 'مورد خارجي')], max_length=50, verbose_name='مصدر التوريد')),
                ('in_quantity', models.IntegerField(default=0, verbose_name='الكمية الواردة')),
                ('live_quantity', models.IntegerField(default=0, verbose_name='الكمية الحالية')),
                ('term', models.CharField(choices=[('الترم الأول', 'الترم الأول'), ('الترم الثاني', 'الترم الثاني')], max_length=20, verbose_name='الترم الدراسي')),
                ('received_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الاستلام')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'نوع كراسة',
                'verbose_name_plural': 'أنواع الكراسات',
            },
        ),
        migrations.CreateModel(
            name='NotebookAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_assignment', models.PositiveIntegerField(default=0, verbose_name='الكمية المخصصة')),
                ('remaining_quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية المتبقية')),
                ('assigned_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التخصيص')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.classlevel', verbose_name='الصف الدراسي')),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.notebooktype', verbose_name='الكراسة')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.stage', verbose_name='المرحلة الدراسية')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.academicyear', verbose_name='السنة الدراسية')),
            ],
            options={
                'verbose_name': 'تخصيص كراسة',
                'verbose_name_plural': 'تخصيصات الكراسات',
            },
        ),
        migrations.AddConstraint(
            model_name='notebooktype',
            constraint=models.UniqueConstraint(fields=('name', 'description'), name='unique_notebook_type'),
        ),
    ]
