# Generated by Django 3.2 on 2024-02-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_auto_20240222_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebooktype',
            name='size',
            field=models.CharField(default=1, max_length=50, verbose_name='حجم الكراسة'),
            preserve_default=False,
        ),
    ]
