# Generated by Django 3.2 on 2024-02-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0059_notebooktype_size'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notebooktype',
            name='unique_notebook_type',
        ),
        migrations.RemoveField(
            model_name='notebookassignment',
            name='due_date',
        ),
        migrations.AddConstraint(
            model_name='notebooktype',
            constraint=models.UniqueConstraint(fields=('name', 'size'), name='unique_notebook_type'),
        ),
    ]
