# Generated by Django 3.2 on 2024-02-26 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0063_alter_stage_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.stage', verbose_name='المرحلة'),
            preserve_default=False,
        ),
    ]
