# Generated by Django 3.2 on 2024-02-27 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0064_classroom_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebookassignment',
            name='remaining_quantity',
        ),
    ]
