# Generated by Django 3.2 on 2024-02-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0066_alter_book_available_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='available_quantity',
            field=models.PositiveIntegerField(verbose_name='الكمية المتاحة'),
        ),
    ]
