# Generated by Django 3.2 on 2024-03-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0067_alter_book_available_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdistribution',
            name='notebooks',
            field=models.ManyToManyField(to='store.NotebookAssignment', verbose_name='الكراسات المسلمة'),
        ),
    ]
