# Generated by Django 3.2 on 2024-04-12 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0069_alter_bookdistribution_notebooks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdistribution',
            name='is_delivered_completely',
        ),
    ]
