# Generated by Django 3.2 on 2024-04-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0070_remove_bookdistribution_is_delivered_completely'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='stage',
            field=models.CharField(choices=[('تمهيدى', 'تمهيدى'), ('رياض الأطفال', 'رياض الأطفال'), ('primry', 'primry'), ('الاعدادية', 'الاعدادية'), ('الثانوية', 'الثانوية')], max_length=50, verbose_name='المرحلة الدراسية'),
        ),
    ]
