# Generated by Django 3.2 on 2024-04-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0071_alter_stage_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdistribution',
            name='booklets',
            field=models.ManyToManyField(blank=True, to='store.SchoolBooklet', verbose_name='البوكليتات المسلمة'),
        ),
        migrations.AlterField(
            model_name='bookdistribution',
            name='books',
            field=models.ManyToManyField(blank=True, to='store.Book', verbose_name='الكتب المسلمة'),
        ),
        migrations.AlterField(
            model_name='bookdistribution',
            name='notebooks',
            field=models.ManyToManyField(blank=True, to='store.NotebookType', verbose_name='الكراسات المسلمة'),
        ),
    ]
