# Generated by Django 3.2 on 2024-05-05 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0073_stockreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockreport',
            old_name='class_level',
            new_name='class_levels',
        ),
        migrations.AlterUniqueTogether(
            name='stockreport',
            unique_together={('stage', 'class_levels', 'academic_year', 'term')},
        ),
    ]
